# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45be3ab4cd698973a3ef58eb0d7ef538"
name = "nyle.ai-1"
handle = "nyle-ai-1"
application_url = "https://store.nyle.ai/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://store.nyle.ai/auth/callback",
  "https://store.nyle.ai/auth/shopify/callback",
  "https://store.nyle.ai/api/auth/callback"
]

[pos]
embedded = false
